### PR TITLE
Accessibility improvements

### PR DESCRIPTION
**Pull request by blunket**
Various improvements for assistive technologies such as screen readers.

### CODE REVIEW

**Comment by srobbin** [comment]
@blunket Thanks so much for submitting this PR. A few thoughts:

* Instead of adding `required` to install and sign_in, let's remove it from account/edit. Validation is handled server-side anyway.
* Let's update sign_in to be `type=email` as well
*  The CircleCI errors are being caused by something unrelated, but if you're up for it ,run `yarn test --updateSnapshot`, and it should fix the problem.

**Comment by blunket** [comment]
Thanks @srobbin! I... *think* I did that right :smiley: let me know if you'd like me to squash all these and force push.

**Comment by srobbin** [comment]
@blunket Sorry for the slow reply—these look great. I'll squash and merge with the next release.

**Comment by blunket** [comment]
Not slow at all! Absolutely no problem, thanks!

**Pull request merged**
