### PR TITLE
Horizontally center header h1 on demo site

### LINKED ISSUE #7: Default site template headline looks strange by default on wide monitors
Win 10, FF62:
image

Just changed "greeting" to `...`. 

Looks ok up until ~1390 width, then the main headline stays at the same position instead of staying centered.

### PR DESCRIPTION
**Pull request by seanwash**
Fixes #7 

This should do the trick:

- https://c.seanwash.com/80J8eKbsneHd.png
- https://c.seanwash.com/yzRf8VnsVF09.png
- https://c.seanwash.com/DVa36vghW10Z.png

### CODE REVIEW

**Comment by tdenyer** [comment]
I tested this commit in latest Chrome, Firefox, Safari on Mac High Sierra—works great!

**Comment by srobbin** [comment]
@seanwash Another good catch, thank you.

One suggestion: I might recommend making it `margin-left: auto` and `margin-right: auto` instead of `margin: 0 auto`. Currently, there's a 4rem bottom margin. It's not apparent at full height, but when you squish the window vertically, the 4rem helps separate the header from the paragraph text below.

**Comment by seanwash** [comment]
@srobbin You know I had the thought to not use `0 auto` but did it anyway. Thanks for the correction. Updated!

**Comment by trst** [comment]
Wouldn’t `margin: 0 auto 4em;` cut it then?

**Comment by srobbin** [comment]
@trst For sure, that would work too.

Merging this in now. Thanks, @seanwash.

**Comment by LoganDark** [comment]
> Wouldn’t `margin: 0 auto 4em;` cut it then?

@trst that would make the left margin 0...

**Comment by seanwash** [comment]
@LoganDark do it wouldn't, that's just shorthand for `top left/right bottom`. See https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties

**Comment by LoganDark** [comment]
I thought margins were specified from the top and going clockwise?

**Comment by seanwash** [comment]
@LoganDark They are when you specify all 4 units. There are various shorthand properties that you can use like `0 auto` == `top/bottom left/right` and `0 auto 40px` == `top left/right bottom`. Check out that link I shared.

**Comment by LoganDark** [comment]
I understood `0 auto` - the way I thought of it is that it's just repeated to make `0 auto 0 auto`, which puts 0 on the top and bottom and `auto` on the sides. I understand what shorthands _are_, I guess I just didn't understand the 3-value one. I already checked out the link.

Please don't assume.

**Comment by seanwash** [comment]
@LoganDark Didn't mean to make you feel like I was putting you down, was just sharing documentation that clarifies how that shorthand works based on the question you asked. Cheers!

**Comment by LoganDark** [comment]
Sorry if it seems like I'm being a bit harsh, I get defensive easily. Anyway, thanks.

**Pull request merged**
