### PR TITLE
Fix rendering a html page doesn't work anymore without extension suffix

### PR DESCRIPTION
**Pull request by bitterbit**
Solves #184

### CODE REVIEW

**Comment by srobbin** [comment]
Thank you, @bitterbit!

**Comment by JohJakob** [comment]
@bitterbit Thank you! I missed that apparently.

**Comment by bitterbit** [comment]
@JohJakob no worries :)
Cool feature with the xml/rss btw, will surely use it in my next project

**Comment by JohJakob** [comment]
@bitterbit Thanks! Yeah, it’s pretty handy :)

**Pull request merged**
