### PR TITLE
tests: test Node.js 8 and 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by srobbin** [comment]
@DanielRuf I didn't realize you could do this—very cool. How would you recommend I test this before merging?

**Comment by DanielRuf** [comment]
I'll do another push to try to trigger a CircleCI build.

**Comment by srobbin** [comment]
@DanielRuf Were you able to trigger a new CircleCI build? If not, I can try forking this myself.

**Comment by DanielRuf** [comment]
> @DanielRuf Were you able to trigger a new CircleCI build? If not, I can try forking this myself.

I was probably just too busy. Wait a minute.

**Comment by DanielRuf** [comment]
Done ;-)

**Comment by srobbin** [comment]
Boom! Worked like a charm, thank you. Merging now.

**Pull request merged**
